version: '3'
services:
  client_mobile:
    volumes:
      - apk-volume:/client
    build: './client'
    depends_on:
      - db
  client_web:
    volumes:
      - ./client_web/flutter_web_app:/usr/local/flutter_web_app
    build: './client_web'
    depends_on:
      - db
  server:
    build: './server'
    ports:
      - "8080:8080"
    environment:
      - DEBUG=1
    networks:
      - backend
    depends_on:
      - db
  db:
    image: 'mongo'
    volumes:
      - ./server/mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
    networks:
      - backend

networks:
    backend:

volumes:
  apk-volume:
  dbdata: